-- MySQL Script generated by MySQL Workbench
-- Thu Mar  4 16:13:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`video` (
  `idvideo` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(155) NULL,
  PRIMARY KEY (`idvideo`),
  UNIQUE INDEX `idvideo_UNIQUE` (`idvideo` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`nombre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`nombre` (
  `idnombre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idnombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`catGram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`catGram` (
  `idcatGram` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcatGram`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`mot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`mot` (
  `idmot` INT NOT NULL AUTO_INCREMENT,
  `ortho` VARCHAR(75) NOT NULL,
  `lemme` VARCHAR(75) NOT NULL,
  `infover` VARCHAR(75) NULL,
  `nblettres` INT NOT NULL,
  `nbsyll` INT NOT NULL,
  `orthrenv` VARCHAR(45) NOT NULL,
  `video_idvideo` INT NOT NULL,
  `nombre_idnombre` INT NOT NULL,
  `genre_idgenre` INT NOT NULL,
  `catGram_idcatGram` INT NOT NULL,
  PRIMARY KEY (`idmot`),
  UNIQUE INDEX `idword_UNIQUE` (`idmot` ASC) VISIBLE,
  INDEX `fk_mot_video1_idx` (`video_idvideo` ASC) VISIBLE,
  INDEX `fk_mot_nombre1_idx` (`nombre_idnombre` ASC) VISIBLE,
  INDEX `fk_mot_genre1_idx` (`genre_idgenre` ASC) VISIBLE,
  INDEX `fk_mot_catGram1_idx` (`catGram_idcatGram` ASC) VISIBLE,
  CONSTRAINT `fk_mot_video1`
    FOREIGN KEY (`video_idvideo`)
    REFERENCES `new_schema1`.`video` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mot_nombre1`
    FOREIGN KEY (`nombre_idnombre`)
    REFERENCES `new_schema1`.`nombre` (`idnombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mot_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `new_schema1`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mot_catGram1`
    FOREIGN KEY (`catGram_idcatGram`)
    REFERENCES `new_schema1`.`catGram` (`idcatGram`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`theme` (
  `idtheme` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtheme`),
  UNIQUE INDEX `idtheme_UNIQUE` (`idtheme` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`mot_has_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`mot_has_theme` (
  `mot_idmot` INT NOT NULL,
  `theme_idtheme` INT NOT NULL,
  PRIMARY KEY (`mot_idmot`, `theme_idtheme`),
  INDEX `fk_word_has_theme_theme1_idx` (`theme_idtheme` ASC) VISIBLE,
  INDEX `fk_word_has_theme_word_idx` (`mot_idmot` ASC) VISIBLE,
  CONSTRAINT `fk_word_has_theme_word`
    FOREIGN KEY (`mot_idmot`)
    REFERENCES `new_schema1`.`mot` (`idmot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word_has_theme_theme1`
    FOREIGN KEY (`theme_idtheme`)
    REFERENCES `new_schema1`.`theme` (`idtheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`signe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`signe` (
  `idsigne` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idsigne`),
  UNIQUE INDEX `idsigne_UNIQUE` (`idsigne` ASC) VISIBLE,
  UNIQUE INDEX `img_UNIQUE` (`img` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`lettre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`lettre` (
  `idlettre` INT NOT NULL AUTO_INCREMENT,
  `lettre` VARCHAR(5) NOT NULL,
  `signe_idsigne` INT NOT NULL,
  PRIMARY KEY (`idlettre`, `signe_idsigne`),
  UNIQUE INDEX `idletter_UNIQUE` (`idlettre` ASC) VISIBLE,
  UNIQUE INDEX `letter_UNIQUE` (`lettre` ASC) VISIBLE,
  INDEX `fk_letter_signe1_idx` (`signe_idsigne` ASC) VISIBLE,
  CONSTRAINT `fk_letter_signe1`
    FOREIGN KEY (`signe_idsigne`)
    REFERENCES `new_schema1`.`signe` (`idsigne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
