-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 14:04:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lsfproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lsfproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lsfproject` ;
USE `lsfproject` ;

-- -----------------------------------------------------
-- Table `lsfproject`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(155) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idvideo_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsfproject`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsfproject`.`nombre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`nombre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsfproject`.`catGram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`catGram` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `lsfproject`.`signe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`signe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idsigne_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `img_UNIQUE` (`img` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsfproject`.`letter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`letter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `letter` VARCHAR(5) NOT NULL,
  `signe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `signe_id`),
  UNIQUE INDEX `idletter_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `letter_UNIQUE` (`letter` ASC) VISIBLE,
  INDEX `fk_letter_signe1_idx` (`signe_id` ASC) VISIBLE,
  CONSTRAINT `fk_letter_signe1`
    FOREIGN KEY (`signe_id`)
    REFERENCES `lsfproject`.`signe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lsfproject`.`mot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lsfproject`.`mot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ortho` VARCHAR(75) NOT NULL,
  `lemme` VARCHAR(75) NOT NULL,
  `catgram` VARCHAR(45) NULL,
  `genre` VARCHAR(70) NULL,
  `nombre` VARCHAR(45) NULL,
  `infover` VARCHAR(75) NULL,
  `nblettres` INT NULL,
  `nbsyll` INT NULL,
  `orthrenv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idword_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
